- {value: 0.1, unit: V, encoding: DAC8568_VOLTAGE}
- {value: 0.2, unit: V, encoding: DAC8568_VOLTAGE}
- {value: 0.3, unit: V, encoding: DAC8568_VOLTAGE}
- {value: 0.4, unit: V, encoding: DAC8568_VOLTAGE}
- {value: 0.5, unit: V, encoding: DAC8568_VOLTAGE}
- {value: 0.6, unit: V, encoding: DAC8568_VOLTAGE}
